ampl_path: ""
cp_model_path: "qcPlanner/qcOptimizer/ampl_models"
cp_model: "quantum_courrier_cp.mod"
time : 10
verbose : 1
solver : 2
in-file:  "defaultData/default_instance.yaml"
out-file: 'data/sol.out'
result-folder:  'data/results/'